version: 2.1

jobs:
  run_docker_commands:
    docker:
      - image: balenalib/generic-aarch64  # Using the balenalib/generic-aarch64 Docker image
    steps:
      - checkout  # Check out the code from the repository (optional)
      - run:
          name: Pull Docker image and run commands
          command: |
            # Run the commands inside the Docker container
            uname -m
            lscpu

workflows:
  version: 2
  build:
    jobs:
      - run_docker_commands
